/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AI_package;

import UserManage_package.User;
import UserManage_package.UserManager;
import main_package.ButtonJPanel;
import main_package.MyFilefilter;
import main_package.MainJFrame;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButtonMenuItem;
import main_package.AudioFilePlayer;

/**
 *
 * @author Administrator
 */
public class AIJFrame extends javax.swing.JFrame {
    private AIBoard board;
    private Image img;
    private AudioFilePlayer player;
    private User user;
    /**
     * Creates new form AIJFram
     */
    public AIJFrame(int depth,int type,User user) {
        this.user=user;
        initComponents();
        player=new AudioFilePlayer("src/musics/磯村由紀子 (矶村由纪子) - 风居住的街道.mp3");
        board=new AIBoard(depth, type,user);
        buttonGroup.add(lowItem);
        buttonGroup.add(primaryItem);
        buttonGroup.add(midItem);
        buttonGroup.add(highItem);
        setDepth();
        if(depth==1){
            lowItem.setSelected(true);
        }else if(depth==2){
            primaryItem.setSelected(true);
        }else if(depth==3){
            midItem.setSelected(true);
        }else{
            highItem.setSelected(true);
        }
        if(type==ComputerPlayer.MAX)
            AITypeItem.setSelected(true);
        else if(type==ComputerPlayer.MIN)
            AITypeItem.setSelected(false);
        getContentPane().add(board);
        setResizable(false);
        player.start();
    }
    private void setDepth(){
       if(user.getScore()<300){
           primaryItem.setEnabled(false);
           midItem.setEnabled(false);
           highItem.setEnabled(false);
       }else if(user.getScore()<700){
           midItem.setEnabled(false);
           highItem.setEnabled(false);
       }else if(user.getScore()<1200){
           highItem.setEnabled(false);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new ButtonJPanel("src/images/button.jpg");
        startButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        playMusicButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        AIMenu = new javax.swing.JMenu();
        restartItem = new javax.swing.JMenuItem();
        backItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        AIOption = new javax.swing.JMenu();
        DepthMenu = new javax.swing.JMenu();
        lowItem = new javax.swing.JRadioButtonMenuItem();
        primaryItem = new javax.swing.JRadioButtonMenuItem();
        midItem = new javax.swing.JRadioButtonMenuItem();
        highItem = new javax.swing.JRadioButtonMenuItem();
        AITypeItem = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        improveItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("人机对弈");
        setPreferredSize(new java.awt.Dimension(904, 660));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        playMusicButton.setBorderPainted(false);
        playMusicButton.setContentAreaFilled(false);
        playMusicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMusicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(playMusicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(playMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(329, 329, 329))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        AIMenu.setText("菜单");

        restartItem.setText("重新开始");
        restartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartItemActionPerformed(evt);
            }
        });
        AIMenu.add(restartItem);

        backItem.setText("悔棋");
        backItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backItemActionPerformed(evt);
            }
        });
        AIMenu.add(backItem);

        saveItem.setText("保存");
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });
        AIMenu.add(saveItem);
        AIMenu.add(jSeparator1);

        exitItem.setText("退出");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        AIMenu.add(exitItem);

        jMenuBar2.add(AIMenu);

        AIOption.setText("选项");

        DepthMenu.setText("选择难度");

        lowItem.setSelected(true);
        lowItem.setText("低级");
        DepthMenu.add(lowItem);

        primaryItem.setSelected(true);
        primaryItem.setText("初级");
        DepthMenu.add(primaryItem);

        midItem.setSelected(true);
        midItem.setText("中级");
        DepthMenu.add(midItem);

        highItem.setSelected(true);
        highItem.setText("高级");
        DepthMenu.add(highItem);

        AIOption.add(DepthMenu);

        AITypeItem.setSelected(true);
        AITypeItem.setText("AI执黑");
        AIOption.add(AITypeItem);

        jMenuBar2.add(AIOption);

        helpMenu.setText("帮助");

        improveItem.setText("进阶");
        improveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                improveItemActionPerformed(evt);
            }
        });
        helpMenu.add(improveItem);
        helpMenu.add(jSeparator2);

        aboutItem.setText("关于");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutItem);

        jMenuBar2.add(helpMenu);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(!board.getIsEnd())
            board.rollback();
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        player.exit();
        dispose();
        MainJFrame startMenu=new MainJFrame(user);
        startMenu.setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        UserManager um=new UserManager();
        User temp;
        if((temp=um.findUser(user.getLogId()))!=null)
            user=temp;
        setDepth();
        board.restart();
        board.resetIsEnd();
        if(lowItem.isSelected())
            board.setDepth(1);
        if(primaryItem.isSelected())
            board.setDepth(2);
        if(midItem.isSelected())
            board.setDepth(3);
        if(highItem.isSelected())
            board.setDepth(4);
        if(AITypeItem.isSelected()){
            board.setAIColor(ComputerPlayer.MAX);
            board.AIFirst();
        }
        else{
            board.setAIColor(ComputerPlayer.MIN);      
        }

    }//GEN-LAST:event_startButtonActionPerformed

    private void restartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartItemActionPerformed
        startButtonActionPerformed(evt);
    }//GEN-LAST:event_restartItemActionPerformed

    private void backItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backItemActionPerformed
        board.rollback();
    }//GEN-LAST:event_backItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        player.exit();
        dispose();
        MainJFrame startMenu=new MainJFrame(user);
        startMenu.setVisible(true);
    }//GEN-LAST:event_exitItemActionPerformed

    private void improveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_improveItemActionPerformed
        String url = "http://jingyan.baidu.com/article/4e5b3e198bc8b991901e24d0.html";  
        try {  
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);  
        } catch (IOException ee) {  
            ee.printStackTrace();  
        }
    }//GEN-LAST:event_improveItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        JOptionPane.showMessageDialog(this, "By YJL and NY.");
    }//GEN-LAST:event_aboutItemActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        JFileChooser fc=new JFileChooser();
//        fc.setBounds(getX(), getY(), fc.getWidth(), fc.getHeight());
        fc.setFileFilter(new MyFilefilter());
        fc.setSelectedFile(new File(".chess"));
        fc.showSaveDialog(null);
        File f=fc.getSelectedFile();
        if(f!=null){
            board.save(f.getAbsolutePath());
        }
    }//GEN-LAST:event_saveItemActionPerformed

    private void playMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMusicButtonActionPerformed
        if(player.start==false)
            player.start=true;
        else
            player.start=false;
    }//GEN-LAST:event_playMusicButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        System.out.println("AI_package.AIJFrame.formMousePressed()");
    }//GEN-LAST:event_formMousePressed
    public void reload(String url){
        board.reload(url);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AIJFrame(1, 0, new User("1", "1")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AIMenu;
    private javax.swing.JMenu AIOption;
    private javax.swing.JCheckBoxMenuItem AITypeItem;
    private javax.swing.JMenu DepthMenu;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JButton backButton;
    private javax.swing.JMenuItem backItem;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JRadioButtonMenuItem highItem;
    private javax.swing.JMenuItem improveItem;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButtonMenuItem lowItem;
    private javax.swing.JRadioButtonMenuItem midItem;
    private javax.swing.JButton playMusicButton;
    private javax.swing.JRadioButtonMenuItem primaryItem;
    private javax.swing.JMenuItem restartItem;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
