/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_package;

import UserManage_package.User;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class HelpFrame extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form HelpFrame
     */
    public HelpFrame(User user) {
        this.user=user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new main_package.ButtonJPanel("src/images/help.jpg");
        help_lable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AIMenu = new javax.swing.JMenu();
        restartItem = new javax.swing.JMenuItem();
        backItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        AIOption = new javax.swing.JMenu();
        DepthMenu = new javax.swing.JMenu();
        lowItem = new javax.swing.JRadioButtonMenuItem();
        primaryItem = new javax.swing.JRadioButtonMenuItem();
        midItem = new javax.swing.JRadioButtonMenuItem();
        highItem = new javax.swing.JRadioButtonMenuItem();
        AITypeItem = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        improveItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("帮助");
        setPreferredSize(new java.awt.Dimension(579, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(792, 600));

        help_lable.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        help_lable.setText("(1)对局双方各执一色棋子");

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel1.setText("(2)空棋盘开局");

        jLabel2.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel2.setText("(3)黑先、白后，交替下子，每次只能下一子");

        jLabel3.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel3.setText("(4)棋子下在棋盘的空白点上，棋子下定后，不得向其");

        jLabel4.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel4.setText("     它点移动，不得从棋盘上拿掉或拿起另落别处");

        jLabel5.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel5.setText("(5)黑方的第一枚棋子可下在棋盘任意交叉点上");

        jLabel6.setFont(new java.awt.Font("禹卫书法行书简体 ", 0, 18)); // NOI18N
        jLabel6.setText("(6)当斜方向或直方向五子相连，则为胜利");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(help_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(help_lable)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(113, 113, 113)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        AIMenu.setText("菜单");

        restartItem.setText("重新开始");
        restartItem.setEnabled(false);
        restartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartItemActionPerformed(evt);
            }
        });
        AIMenu.add(restartItem);

        backItem.setText("悔棋");
        backItem.setEnabled(false);
        backItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backItemActionPerformed(evt);
            }
        });
        AIMenu.add(backItem);

        saveItem.setText("保存");
        saveItem.setEnabled(false);
        AIMenu.add(saveItem);
        AIMenu.add(jSeparator1);

        exitItem.setText("退出");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        AIMenu.add(exitItem);

        jMenuBar1.add(AIMenu);

        AIOption.setText("选项");

        DepthMenu.setText("选择难度");

        lowItem.setSelected(true);
        lowItem.setText("低级");
        DepthMenu.add(lowItem);

        primaryItem.setSelected(true);
        primaryItem.setText("初级");
        DepthMenu.add(primaryItem);

        midItem.setSelected(true);
        midItem.setText("中级");
        DepthMenu.add(midItem);

        highItem.setSelected(true);
        highItem.setText("高级");
        DepthMenu.add(highItem);

        AIOption.add(DepthMenu);

        AITypeItem.setText("AI执黑");
        AIOption.add(AITypeItem);

        jMenuBar1.add(AIOption);

        helpMenu.setText("帮助");

        improveItem.setText("进阶");
        improveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                improveItemActionPerformed(evt);
            }
        });
        helpMenu.add(improveItem);
        helpMenu.add(jSeparator2);

        aboutItem.setText("关于");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        MainJFrame startMenu=new MainJFrame(user);
        startMenu.setBounds(getBounds());
        startMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void restartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartItemActionPerformed

    }//GEN-LAST:event_restartItemActionPerformed

    private void backItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backItemActionPerformed

    }//GEN-LAST:event_backItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void improveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_improveItemActionPerformed
        String url = "http://jingyan.baidu.com/article/4e5b3e198bc8b991901e24d0.html";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
        } catch (IOException ee) {
            ee.printStackTrace();
        }
    }//GEN-LAST:event_improveItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        JOptionPane.showMessageDialog(this, "By YJL and NY.");
    }//GEN-LAST:event_aboutItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AIMenu;
    private javax.swing.JMenu AIOption;
    private javax.swing.JCheckBoxMenuItem AITypeItem;
    private javax.swing.JMenu DepthMenu;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem backItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel help_lable;
    private javax.swing.JRadioButtonMenuItem highItem;
    private javax.swing.JMenuItem improveItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButtonMenuItem lowItem;
    private javax.swing.JRadioButtonMenuItem midItem;
    private javax.swing.JRadioButtonMenuItem primaryItem;
    private javax.swing.JMenuItem restartItem;
    private javax.swing.JMenuItem saveItem;
    // End of variables declaration//GEN-END:variables
}
