/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_package;

import doublePlayer_package.PlayerCompeteJFrame;
import AI_package.AIJFrame;
import AI_package.ComputerPlayer;
import UserManage_package.InfoFrame;
import UserManage_package.User;
import doublePlayer_package.LobbyFrame;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MainJFrame extends javax.swing.JFrame {
    private User user;
    private String level;
    /**
     * Creates new form NewJFrame
     */
    public MainJFrame(User user) {
        this.user=user;
        initComponents();
        buttonGroup.add(lowItem);
        buttonGroup.add(primaryItem);
        buttonGroup.add(midItem);
        buttonGroup.add(highItem);
        lowItem.setSelected(true);
        setDepth();
        setResizable(false);
    }
    private void setDepth(){
       if(user.getScore()<300){
           primaryItem.setEnabled(false);
           midItem.setEnabled(false);
           highItem.setEnabled(false);
       }else if(user.getScore()<700){
           midItem.setEnabled(false);
           highItem.setEnabled(false);
       }else if(user.getScore()<1200){
           highItem.setEnabled(false);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new main_package.ButtonJPanel("src/images/start.jpg");
        single_player = new javax.swing.JButton();
        read_button = new javax.swing.JButton();
        help_button = new javax.swing.JButton();
        two_players = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        AIMenu = new javax.swing.JMenu();
        showInfoItem = new javax.swing.JMenuItem();
        restartItem = new javax.swing.JMenuItem();
        backItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        AIOption = new javax.swing.JMenu();
        DepthMenu = new javax.swing.JMenu();
        lowItem = new javax.swing.JRadioButtonMenuItem();
        primaryItem = new javax.swing.JRadioButtonMenuItem();
        midItem = new javax.swing.JRadioButtonMenuItem();
        highItem = new javax.swing.JRadioButtonMenuItem();
        AITypeItem = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        improveItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("基于博弈树的五子棋");

        single_player.setFont(new java.awt.Font("楷体", 1, 18)); // NOI18N
        single_player.setBorderPainted(false);
        single_player.setContentAreaFilled(false);
        single_player.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        single_player.setPreferredSize(new java.awt.Dimension(100, 27));
        single_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                single_playerActionPerformed(evt);
            }
        });

        read_button.setFont(new java.awt.Font("楷体", 1, 18)); // NOI18N
        read_button.setBorderPainted(false);
        read_button.setContentAreaFilled(false);
        read_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_buttonActionPerformed(evt);
            }
        });

        help_button.setFont(new java.awt.Font("楷体", 1, 18)); // NOI18N
        help_button.setBorderPainted(false);
        help_button.setContentAreaFilled(false);
        help_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_buttonActionPerformed(evt);
            }
        });

        two_players.setFont(new java.awt.Font("楷体", 1, 18)); // NOI18N
        two_players.setBorderPainted(false);
        two_players.setContentAreaFilled(false);
        two_players.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two_players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                two_playersMouseClicked(evt);
            }
        });
        two_players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_playersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(single_player, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(two_players, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(help_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(single_player, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(two_players, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(read_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(help_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        AIMenu.setText("菜单");

        showInfoItem.setText("查看个人信息");
        showInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfoItemActionPerformed(evt);
            }
        });
        AIMenu.add(showInfoItem);

        restartItem.setText("重新开始");
        restartItem.setEnabled(false);
        restartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartItemActionPerformed(evt);
            }
        });
        AIMenu.add(restartItem);

        backItem.setText("悔棋");
        backItem.setEnabled(false);
        backItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backItemActionPerformed(evt);
            }
        });
        AIMenu.add(backItem);

        saveItem.setText("保存");
        saveItem.setEnabled(false);
        AIMenu.add(saveItem);
        AIMenu.add(jSeparator1);

        exitItem.setText("退出");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        AIMenu.add(exitItem);

        jMenuBar2.add(AIMenu);

        AIOption.setText("选项");

        DepthMenu.setText("选择难度");

        lowItem.setSelected(true);
        lowItem.setText("低级");
        DepthMenu.add(lowItem);

        primaryItem.setSelected(true);
        primaryItem.setText("初级");
        DepthMenu.add(primaryItem);

        midItem.setSelected(true);
        midItem.setText("中级");
        DepthMenu.add(midItem);

        highItem.setSelected(true);
        highItem.setText("高级");
        DepthMenu.add(highItem);

        AIOption.add(DepthMenu);

        AITypeItem.setText("AI执黑");
        AIOption.add(AITypeItem);

        jMenuBar2.add(AIOption);

        helpMenu.setText("帮助");

        improveItem.setText("进阶");
        improveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                improveItemActionPerformed(evt);
            }
        });
        helpMenu.add(improveItem);
        helpMenu.add(jSeparator2);

        aboutItem.setText("关于");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutItem);

        jMenuBar2.add(helpMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void single_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_single_playerActionPerformed
        Object[] choice={"黑棋","白棋"};
        Object select=JOptionPane.showInputDialog(null, "您要选择黑棋还是白棋?", "选择是否先手",
                JOptionPane.INFORMATION_MESSAGE,null,choice,choice[0]);
        if(select==null)
            return;
        int depth=1,type;
        if(lowItem.isSelected())
            depth=1;
        if(primaryItem.isSelected())
            depth=2;
        if(midItem.isSelected())
            depth=3;
        if(highItem.isSelected())
            depth=4;
        if(select.equals(choice[0])){
            type=ComputerPlayer.MIN;
        }
        else if(select.equals(choice[1])){
            type=ComputerPlayer.MAX;      
        }else{
            return;
        }
        dispose();
        AIJFrame AI_compete=new AIJFrame(depth,type,user);
        AI_compete.setVisible(true);
    }//GEN-LAST:event_single_playerActionPerformed

    private void read_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_buttonActionPerformed
        JFileChooser fc=new JFileChooser();
//        fc.setBounds(getX(), getY(), fc.getWidth(), fc.getHeight());
        fc.setFileFilter(new MyFilefilter());
        fc.showOpenDialog(null);
        File f=fc.getSelectedFile();
        if(f!=null){
            //判断棋局是人机对战还是人人对战
            int x=-3,y=-3,type=0;
            InputStream is=null;
            ObjectInputStream ois=null;
            try {
                is=new FileInputStream(f);
                ois=new ObjectInputStream(is);
                Point p=(Point)ois.readObject();
                x=p.getX();
                y=p.getY();
                type=p.getType();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dispose();
            if(x==-1&&y==-1){
//                PlayerCompeteJFrame player_compete=new PlayerCompeteJFrame(user);
//                player_compete.setVisible(true);
//                player_compete.reload(f.getAbsolutePath());
            }else if(x==-2&&y==-2){
                AIJFrame AI=new AIJFrame(2, type,user);
                AI.setVisible(true);
                AI.reload(f.getAbsolutePath());
            }else{
                System.err.println("读取文件错误");
            }
            
        }
    }//GEN-LAST:event_read_buttonActionPerformed

    private void two_playersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two_playersMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_two_playersMouseClicked

    private void two_playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_playersActionPerformed
        dispose();
        LobbyFrame lf=new LobbyFrame(user);
        lf.setVisible(true);
    }//GEN-LAST:event_two_playersActionPerformed

    private void help_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_buttonActionPerformed
        dispose();
        HelpFrame helpFrame=new HelpFrame(user);
        helpFrame.setVisible(true);
        helpFrame.setSize(getSize());
        helpFrame.setBounds(getBounds());
    }//GEN-LAST:event_help_buttonActionPerformed

    private void restartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartItemActionPerformed
        
    }//GEN-LAST:event_restartItemActionPerformed

    private void backItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backItemActionPerformed
        
    }//GEN-LAST:event_backItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void improveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_improveItemActionPerformed
        String url = "http://jingyan.baidu.com/article/4e5b3e198bc8b991901e24d0.html";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
        } catch (IOException ee) {
            ee.printStackTrace();
        }
    }//GEN-LAST:event_improveItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        JOptionPane.showMessageDialog(this, "By YJL and NY.");
    }//GEN-LAST:event_aboutItemActionPerformed

    private void showInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfoItemActionPerformed
        // TODO add your handling code here:
        new InfoFrame(user).setVisible(true);
    }//GEN-LAST:event_showInfoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AIMenu;
    private javax.swing.JMenu AIOption;
    private javax.swing.JCheckBoxMenuItem AITypeItem;
    private javax.swing.JMenu DepthMenu;
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem backItem;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton help_button;
    private javax.swing.JRadioButtonMenuItem highItem;
    private javax.swing.JMenuItem improveItem;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButtonMenuItem lowItem;
    private javax.swing.JRadioButtonMenuItem midItem;
    private javax.swing.JRadioButtonMenuItem primaryItem;
    private javax.swing.JButton read_button;
    private javax.swing.JMenuItem restartItem;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JMenuItem showInfoItem;
    private javax.swing.JButton single_player;
    private javax.swing.JButton two_players;
    // End of variables declaration//GEN-END:variables
}
